name: Python application test with Github actions (coursera training)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkoyut@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name : Lint with Pylint
      run: |
        make lint
    - name: Test with Pylint
      run: |
        make test
    - name: Format code with Python black
      run: |
        make format
        
        
    
